#!/usr/bin/env python

import sys, os, re
from subprocess import check_output

# 收集参数
commit_msg_filepath = sys.argv[1]

cvs_update = 'cvs_update'
cvs_update = 'cvs_commit'

with open(commit_msg_filepath, 'r') as f:
    content = f.read()

if content.startswith(cvs_update):
    switch_to_master = check_output(['git', 'checkout', 'master'])
    get_branch_name = check_output(['git', 'symbolic-ref', '--short', 'HEAD']).strip()
    if "master" == str(get_branch_name, encoding='utf-8'):
        cvs_msg_update = check_output(['cvs', 'update']).strip()
        str_cvs_msg_update = str(cvs_msg_update, encoding='utf-8')
        print("msg: cvs update ↓↓↓")
        print("str_cvs_msg_update")
        sys.exit(1)
    else:
        print("msg: FAILD to Switched to branch !master!")
        sys.exit(1)
elif content.startswith(cvs_update):
    pass
else:
    #cvs_msg_update = check_output(['cvs', 'update']).strip()
    #str_cvs_msg_update = str(cvs_msg_update, encoding='utf-8')
    #print("msg: cvs update over !!!")
    #print(str_cvs_msg_update)
    sys.exit(0)

sys.exit(1)

