#!/usr/bin/env python

import sys, os, re
from subprocess import check_output

print("Jiuzhen.An Push")

get_branch_name = check_output(['git', 'symbolic-ref', '--short', 'HEAD']).strip()

if "master" == str(get_branch_name, encoding='utf-8'):
    cvs_msg_update = check_output(['cvs', 'update']).strip()
    str_cvs_msg_update = str(cvs_msg_update, encoding='utf-8')
    print("msg: cvs update ↓↓↓")
    print("str_cvs_msg_update")
    sys.exit(1)
else:
    print("msg: FAILD to Switched to branch !master!")

sys.exit(1)
