#!/usr/bin/env python

import sys, os, re
from subprocess import check_output

#检测我们所在的分支
branch = check_output(['git', 'symbolic-ref', '--short', 'HEAD']).strip()
str_branch = str(branch, encoding='utf-8')
#print("post-merge: On branch: '%s'" % branch)

if str_branch != 'master':
    print('pre-commit:not master')
    #stash = check_output(['git', 'stash', 'save']).strip()
    #str_stash = str(stash, encoding='utf-8')
    #print(str_stash)
    #check_output(['git', 'checkout', 'master'])
    #print(check_output(['git', 'symbolic-ref', '--short', 'HEAD']).strip())
else:
    print('It is on master branch')

sys.exit(0)